### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by braden337** [zhodamx/zhodamx.github.io#1]
- [x] create hello world index.html
- [x] create Jekyll folder structure
- [x] get gulp set up and working perfect (browserSync)
- [ ] duplicate styles from original website
- [ ] style google [forms](http://morning.am/tutorials/how-to-style-google-forms/)
